const API_KEY = import.meta.env.VITE_TMDB_API_KEY;

const requests = {
  fetchNetflixOriginals:
    `/discover/tv?api_key=${API_KEY}&with_networks=213`,
  fetchTrending:
    `/trending/all/week?api_key=${API_KEY}`,
  fetchTopRated:
    `/movie/top_rated?api_key=${API_KEY}`,
  fetchTrendingTV:
    `/trending/tv/week?api_key=${API_KEY}`,
  fetchTrendingMovies:
    `/trending/movie/week?api_key=${API_KEY}`,
  fetchPopularMovies: 
    `/movie/popular?api_key=${API_KEY}`, 
  fetchUpcomingMovies: 
    `/movie/upcoming?api_key=${API_KEY}`, 
  //Movies
  fetchActionMovies:
    `/discover/movie?api_key=${API_KEY}&with_genres=28`,
  fetchHorrorMovies:
    `/discover/movie?api_key=${API_KEY}&with_genres=27`,
  fetchComedyMovies:
    `/discover/movie?api_key=${API_KEY}&with_genres=35`,
  fetchAdventureMovies:
    `/discover/movie?api_key=${API_KEY}&with_genres=12`,
  fetchSciFiMovies:
    `/discover/movie?api_key=${API_KEY}&with_genres=878`,
  fetchAnimatedMovies:
    `/discover/movie?api_key=${API_KEY}&with_genres=16`,
  fetchWarMovies:
    `/discover/movie?api_key=${API_KEY}&with_genres=10752`,
  fetchRomanceMovies:
    `/discover/movie?api_key=${API_KEY}&with_genres=10749`,
  fetchThrillerMovies:
    `/discover/movie?api_key=${API_KEY}&with_genres=53`,
  fetchDocumentryMovies:
    `/discover/movie?api_key=${API_KEY}&with_genres=99`,
  //Shows
    fetchActionndAdventureShows:
    `/discover/tv?api_key=${API_KEY}&with_genres=10759`,
  fetchComedyShows:
    `/discover/tv?api_key=${API_KEY}&with_genres=35`,
  fetchMysteryShows:
    `/discover/tv?api_key=${API_KEY}&with_genres=9648`,
  fetchSciFindFantasyShows:
    `/discover/tv?api_key=${API_KEY}&with_genres=10765`,
  fetchDramaShows:
    `/discover/tv?api_key=${API_KEY}&with_genres=18`,
  fetchFamily:
    `/discover/tv?api_key=${API_KEY}&with_genres=10751`,
  fetchDocumentry:
    `/discover/tv?api_key=${API_KEY}&with_genres=99`,
  //Kids
  fetchKidsAnimationTV:
    `/discover/tv?api_key=${API_KEY}&with_genres=16&sort_by=popularity.desc&include_adult=false&vote_count.gte=50`,
  fetchKidsTV:
    `/discover/tv?api_key=${API_KEY}&with_genres=10762&sort_by=popularity.desc&include_adult=false&vote_count.gte=50`,
  fetchFamilyTV:
    `/discover/tv?api_key=${API_KEY}&with_genres=10751&sort_by=popularity.desc&include_adult=false&vote_count.gte=50`,
  fetchKidsComedyTV:
    `/discover/tv?api_key=${API_KEY}&with_genres=35&sort_by=popularity.desc&include_adult=false&vote_count.gte=50`,
  fetchNetflixKidsOriginals:
    `/discover/tv?api_key=${API_KEY}&with_networks=213&with_genres=16,10762&sort_by=popularity.desc&include_adult=false&vote_count.gte=50`,
  fetchKidsMovies:
  `/discover/movie?api_key=${API_KEY}&with_genres=16,10751,35,14&sort_by=popularity.desc&include_adult=false&vote_count.gte=50`,
};
export default requests;
